In [4]:
# defining the address/location of the file
file_path = r"C:\Users\HP\Downloads\orders_details.csv"

In [1]:
file_path = r"C:\Users\HP\Downloads\Loan_prediction_dataset.csv"

In [9]:
import numpy as np

In [13]:
file = open(file_path, "r")

print(file.read())
            

Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
LP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y
LP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N
LP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y
LP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N
LP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y
LP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y
LP001028,Male,Yes,2,Graduate,No,3073,8106,200,360,1,Urban,Y
LP001029,Male,No,0,Graduate,No,1853,2840,114,360,1,Rural,N

- r = READ MODE
- w = WRITE MODE
- a = APPEND MODE
- x = CREATE MODE
- b = BINARY MODE
- t = TEXT MODE

In [22]:
file = open(file_path, "r")

file.read()

'orderid,productid,unitprice,quantity,discount\n10248,11,14,12,0\n10248,42,9.8,10,0\n10248,72,34.8,5,0\n10249,14,18.6,9,0\n10249,51,42.4,40,0\n10250,41,7.7,10,0\n10250,51,42.4,35,0.15\n10250,65,16.8,15,0.15\n10251,22,16.8,6,0.05\n10251,57,15.6,15,0.05\n10251,65,16.8,20,0\n10252,20,64.8,40,0.05\n10252,33,2,25,0.05\n10252,60,27.2,40,0\n10253,31,10,20,0\n10253,39,14.4,42,0\n10253,49,16,40,0\n10254,24,3.6,15,0.15\n10254,55,19.2,21,0.15\n10254,74,8,21,0\n10255,2,15.2,20,0\n10255,16,13.9,35,0\n10255,36,15.2,25,0\n10255,59,44,30,0\n10256,53,26.2,15,0\n10256,77,10.4,12,0\n10257,27,35.1,25,0\n10257,39,14.4,6,0\n10257,77,10.4,15,0\n10258,2,15.2,50,0.2\n10258,5,17,65,0.2\n10258,32,25.6,6,0.2\n10259,21,8,10,0\n10259,37,20.8,1,0\n10260,41,7.7,16,0.25\n10260,57,15.6,50,0\n10260,62,39.4,15,0.25\n10260,70,12,21,0.25\n10261,21,8,20,0\n10261,35,14.4,20,0\n10262,5,17,12,0.2\n10262,7,24,15,0\n10262,56,30.4,2,0\n10263,16,13.9,60,0.25\n10263,24,3.6,28,0\n10263,30,20.7,60,0.25\n10263,74,8,36,0.25\n10264,2,15

In [24]:
x = "tobi"

In [26]:
x

'tobi'

In [28]:
print(x)

tobi


In [32]:
def greet_me():
    print("Hello Tobi")

In [36]:
greet_me()

Hello Tobi


In [38]:
greet_1 = greet_me()
print(greet_1)

Hello Tobi
None


In [40]:
print(greet_1)

None


In [42]:
def greet_me2():
    return "Hello Tobi"

In [44]:
greet_2 = greet_me2()

In [50]:
greet_2
greet_2
greet_2

'Hello Tobi'

In [52]:
print(greet_2)
print(greet_2)
print(greet_2)

Hello Tobi
Hello Tobi
Hello Tobi


---

In [55]:
file = open(file_path, "r")
print(file.read())
file.close()

orderid,productid,unitprice,quantity,discount
10248,11,14,12,0
10248,42,9.8,10,0
10248,72,34.8,5,0
10249,14,18.6,9,0
10249,51,42.4,40,0
10250,41,7.7,10,0
10250,51,42.4,35,0.15
10250,65,16.8,15,0.15
10251,22,16.8,6,0.05
10251,57,15.6,15,0.05
10251,65,16.8,20,0
10252,20,64.8,40,0.05
10252,33,2,25,0.05
10252,60,27.2,40,0
10253,31,10,20,0
10253,39,14.4,42,0
10253,49,16,40,0
10254,24,3.6,15,0.15
10254,55,19.2,21,0.15
10254,74,8,21,0
10255,2,15.2,20,0
10255,16,13.9,35,0
10255,36,15.2,25,0
10255,59,44,30,0
10256,53,26.2,15,0
10256,77,10.4,12,0
10257,27,35.1,25,0
10257,39,14.4,6,0
10257,77,10.4,15,0
10258,2,15.2,50,0.2
10258,5,17,65,0.2
10258,32,25.6,6,0.2
10259,21,8,10,0
10259,37,20.8,1,0
10260,41,7.7,16,0.25
10260,57,15.6,50,0
10260,62,39.4,15,0.25
10260,70,12,21,0.25
10261,21,8,20,0
10261,35,14.4,20,0
10262,5,17,12,0.2
10262,7,24,15,0
10262,56,30.4,2,0
10263,16,13.9,60,0.25
10263,24,3.6,28,0
10263,30,20.7,60,0.25
10263,74,8,36,0.25
10264,2,15.2,35,0
10264,41,7.7,25,0.15
10265,17,31.2,30,0
1

In [57]:
with open(file_path, "r") as file:
    print(file.read())

orderid,productid,unitprice,quantity,discount
10248,11,14,12,0
10248,42,9.8,10,0
10248,72,34.8,5,0
10249,14,18.6,9,0
10249,51,42.4,40,0
10250,41,7.7,10,0
10250,51,42.4,35,0.15
10250,65,16.8,15,0.15
10251,22,16.8,6,0.05
10251,57,15.6,15,0.05
10251,65,16.8,20,0
10252,20,64.8,40,0.05
10252,33,2,25,0.05
10252,60,27.2,40,0
10253,31,10,20,0
10253,39,14.4,42,0
10253,49,16,40,0
10254,24,3.6,15,0.15
10254,55,19.2,21,0.15
10254,74,8,21,0
10255,2,15.2,20,0
10255,16,13.9,35,0
10255,36,15.2,25,0
10255,59,44,30,0
10256,53,26.2,15,0
10256,77,10.4,12,0
10257,27,35.1,25,0
10257,39,14.4,6,0
10257,77,10.4,15,0
10258,2,15.2,50,0.2
10258,5,17,65,0.2
10258,32,25.6,6,0.2
10259,21,8,10,0
10259,37,20.8,1,0
10260,41,7.7,16,0.25
10260,57,15.6,50,0
10260,62,39.4,15,0.25
10260,70,12,21,0.25
10261,21,8,20,0
10261,35,14.4,20,0
10262,5,17,12,0.2
10262,7,24,15,0
10262,56,30.4,2,0
10263,16,13.9,60,0.25
10263,24,3.6,28,0
10263,30,20.7,60,0.25
10263,74,8,36,0.25
10264,2,15.2,35,0
10264,41,7.7,25,0.15
10265,17,31.2,30,0
1

In [61]:
file_path = r"C:\Users\HP\OneDrive\Desktop\My name is Tobi.txt"
with open(file_path, "r") as file:
    print(file.read())

My name is Tobi


In [65]:
file_path = r"C:\Users\HP\OneDrive\Desktop\My name is Tobi.txt"
with open(file_path, "w") as file:
    file.write("My name is Samuel")

In [67]:
file_path = r"C:\Users\HP\OneDrive\Desktop\My name is Tobi.txt"
with open(file_path, "r") as file:
    print(file.read())

My name is Samuel


In [69]:
file_path = r"C:\Users\HP\OneDrive\Desktop\My name is Tobi.txt"
with open(file_path, "a") as file:
    file.write("My name is Tobiloba")

In [71]:
file_path = r"C:\Users\HP\OneDrive\Desktop\My name is Tobi.txt"
with open(file_path, "r") as file:
    print(file.read())

My name is SamuelMy name is Tobiloba


In [75]:
file_path = r"C:\Users\HP\OneDrive\Desktop\My name is Tobi.txt"
with open(file_path, "a") as file:
    file.write("\nMy name is Tobi")

---

In [80]:
file_path = r"C:\Users\HP\Downloads\orders_details.csv"
file = open(file_path, "r")
print(file.read())

orderid,productid,unitprice,quantity,discount
10248,11,14,12,0
10248,42,9.8,10,0
10248,72,34.8,5,0
10249,14,18.6,9,0
10249,51,42.4,40,0
10250,41,7.7,10,0
10250,51,42.4,35,0.15
10250,65,16.8,15,0.15
10251,22,16.8,6,0.05
10251,57,15.6,15,0.05
10251,65,16.8,20,0
10252,20,64.8,40,0.05
10252,33,2,25,0.05
10252,60,27.2,40,0
10253,31,10,20,0
10253,39,14.4,42,0
10253,49,16,40,0
10254,24,3.6,15,0.15
10254,55,19.2,21,0.15
10254,74,8,21,0
10255,2,15.2,20,0
10255,16,13.9,35,0
10255,36,15.2,25,0
10255,59,44,30,0
10256,53,26.2,15,0
10256,77,10.4,12,0
10257,27,35.1,25,0
10257,39,14.4,6,0
10257,77,10.4,15,0
10258,2,15.2,50,0.2
10258,5,17,65,0.2
10258,32,25.6,6,0.2
10259,21,8,10,0
10259,37,20.8,1,0
10260,41,7.7,16,0.25
10260,57,15.6,50,0
10260,62,39.4,15,0.25
10260,70,12,21,0.25
10261,21,8,20,0
10261,35,14.4,20,0
10262,5,17,12,0.2
10262,7,24,15,0
10262,56,30.4,2,0
10263,16,13.9,60,0.25
10263,24,3.6,28,0
10263,30,20.7,60,0.25
10263,74,8,36,0.25
10264,2,15.2,35,0
10264,41,7.7,25,0.15
10265,17,31.2,30,0
1

In [94]:
print(order_details)

[[       nan        nan        nan        nan        nan]
 [1.0248e+04 1.1000e+01 1.4000e+01 1.2000e+01 0.0000e+00]
 [1.0248e+04 4.2000e+01 9.8000e+00 1.0000e+01 0.0000e+00]
 ...
 [1.1077e+04 7.3000e+01 1.5000e+01 2.0000e+00 1.0000e-02]
 [1.1077e+04 7.5000e+01 7.7500e+00 4.0000e+00 0.0000e+00]
 [1.1077e+04 7.7000e+01 1.3000e+01 2.0000e+00 0.0000e+00]]


In [82]:
import numpy as np

In [92]:
file_path = r"C:\Users\HP\Downloads\orders_details.csv"
order_details = np.genfromtxt(file_path, delimiter=",")

In [98]:
order_details[0]

array([nan, nan, nan, nan, nan])

In [100]:
order_details[0,3]

nan

In [96]:
print(order_details.shape)

(2156, 5)


In [104]:
order_details[1:,3]

array([12., 10.,  5., ...,  2.,  4.,  2.])

In [106]:
quantity = order_details[1:,3]

In [108]:
print(sum(quantity))

51317.0


In [110]:
print(quantity.sum())

51317.0


In [114]:
prices = {'apple': 0.40, 'orange': 0.35, 'banana': 0.25}
for key in list (prices.keys()):
    if key == 'orange':
        del prices[key]

In [116]:
print(prices)

{'apple': 0.4, 'banana': 0.25}


In [ ]:
print("The square of", number, "is", number*number)

In [ ]:
while True:
    user_input = input("Enter a number (or 'q' to quit): ")
if user_input == 'q':
    break
else:
    number = int(user_input)
    print("The square of", number, "is", number*number)

In [153]:
while True:
    user_input = input("Enter a number (or 'q' to quit): ")
     if user_input == 'q':
        break
    try:
        number = int(user_input)
        print("The square of", number, "is", number * number)
    except ValueError:
        print("Please enter a valid number or 'q' to quit.")

KeyboardInterrupt: Interrupted by user

In [165]:
while True:
    user_input = input("Enter a number (or 'q' to quit): ")
    if user_input == 'q':
        break
    else:
        number = int(user_input)
        print("The square of", number, "is", number*number)

Enter a number (or 'q' to quit):  5


The square of 5 is 25


Enter a number (or 'q' to quit):  q
